"""
Django settings for MAC project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env file automatically if present
env_file = BASE_DIR / '.env'
if env_file.exists():
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                os.environ.setdefault(key.strip(), value.strip().strip("'\""))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-i9vqeq@=)ck786n94i8cap8_hztdz1yks0(uye3@8k_l-)uz!m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 't')

# ALLOWED_HOSTS configured via environment variable (comma-separated, e.g. "localhost,127.0.0.1,my-app.onrender.com")
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # ⚡ MUST BE FIRST
    'shop.apps.ShopConfig', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ⚡ Serves static files (Jazzmin + admin CSS) on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MAC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'shop' / 'templates',
            BASE_DIR / 'blog' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MAC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Managing Media (Images, documents uploaded by users)

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Razorpay Configuration via Environment Variables with Local Test Fallbacks
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', 'rzp_test_TB2BNYNjbRlDij')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', 'vYJVMaXp5zoB82XsQDdXklg6')

# =========================================================================
# 🎨 Jazzmin Modern SaaS Admin Theme Configuration
# =========================================================================
JAZZMIN_SETTINGS = {
    "site_title": "OQIREL Admin",
    "site_header": "Boutique Panel",
    "site_brand": "OQIREL Panel",
    "welcome_sign": "Welcome back to OQIREL",
    "search_model": ["shop.Product", "blog.BlogPost", "shop.Order"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Live Storefront", "url": "/shop/"},
        {"name": "Editorial Journal", "url": "/blog/"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_css": "shop/css/custom_admin.css",
    "icons": {
        "auth.user": "fas fa-users-cog",
        "shop.Product": "fas fa-spa",
        "shop.Wishlist": "fas fa-heart",
        "shop.Order": "fas fa-shopping-bag",
        "shop.Contact": "fas fa-envelope-open-text",
        "shop.OrderUpdate": "fas fa-truck-loading",
        "blog.BlogPost": "fas fa-feather-alt",
        "blog.BlogComment": "fas fa-comments",
    },
}

# 🎨 Native UI Tweak Layer Matching Our Pastel Editorial Aesthetic
JAZZMIN_UI_TWEAKS = {
    # 🌟 Uses the clean, minimalist "Simplex" skin archetype (soft nude tones/serif compliance)
    "theme": "simplex", 
    "dark_mode_theme": None,
    
    # 🧭 Top Header Navbar Styles
    "navbar": "navbar-dark bg-brown", # Handled via global custom asset sheet
    "navbar_fixed": True,
    
    # 👥 Left Sidebar Panel Setup
    "sidebar": "sidebar-light-primary", # Light pastel background framing
    "sidebar_fixed": True,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_child_indent": True,
    
    # Buttons and Badges Accent Core Colors
    "button_classes": {
        "primary": "btn-outline-primary rounded-pill",
        "secondary": "btn-outline-secondary rounded-pill",
        "success": "btn-success rounded-pill px-3", # Handled via pastel mint green
        "danger": "btn-danger rounded-pill",
    }
}


