# Generated by Django 6.0.1 on 2026-07-27 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
